config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: { sessions: 'clients/sessions' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  resources :services
  resources :products

  get '/clients/:id', :to => 'clients#show', :as => :client, via: :get
  get '/clients/:id/my_orders', :to => 'clients#my_orders', as: :my_orders, via: :get

  get '/admins/:id', :to => 'admins#show', :as => :admin, via: :get
  get '/admins/:id/show_clients', :to => 'admins#show_clients', as: :show_clients, via: :get
  get '/admins/:id/show_products', :to => 'admins#show_products', as: :show_products, via: :get
  get '/admins/:id/show_services', :to => 'admins#show_services', as: :show_services, via: :get

  root 'pages#start'

end

app/views/layouts/_admin_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <%= link_to admin_path(current_admin), class: "logo" do %>
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>ME</b>J</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Eletron</b>jun</span>
  <% end %>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-chevron-right"></i> Sair
          </a>
          <ul class="dropdown-menu">
            <li class="header">Opções para o Administrador</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <%= link_to root_path do %>
                   <i class="fa fa-reply text-aqua"></i> Voltar para o Início
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                    <i class="fa fa-power-off text-red"></i> Log Out
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i> Menu do Administrador
          </a>
          <ul class="dropdown-menu">
            <li class="header">Opções para o Administrador</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                   <i class="fa fa-users text-aqua"></i> Gerenciar Serviços
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> Gerenciar Produtos
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> Gerenciar Clientes
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-phone text-red"></i> Solicitar Suporte
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="hidden-xs"><i class="fa fa-building"></i> Eletronjun</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag("/images/logo_small_eletronjun.png", alt: "Logo Eletronjun") %>
              <p>
                EletronJun
                <small>Engenharia Eletrônica Júnior</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-6 text-center">
                  <a href="http://eletronjun.com.br/"><i class="fa fa-check-circle text-green"></i> Site Oficial</a>
                </div>
                <div class="col-xs-6 text-center">
                  <a href="https://www.facebook.com/eletronjun/"><i class="fa fa-facebook text-blue"></i> Facebook</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_sidebar_left.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/images/logo_small_eletronjun.png" class="img-circle" alt="User Image" style="max-width: 56px;">
      </div>
      <div class="pull-left info">
        <p>Administrador</p>
        <small><i class="fa fa-circle text-success"></i> Online</small>
      </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Buscar...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MENU DE NAVEGAÇÃO</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-pie-chart"></i>
          <span>Painel do Gerente</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to admin_path(current_admin) do %>
              <i class="fa fa-circle-o"></i> Painel de Controle Geral</li>
            <% end %>
          <li>
            <%= link_to show_products_path(current_admin) do %>
              <i class="fa fa-circle-o"></i> Produtos
            <% end %>
          </li>
          <li>
            <%= link_to show_services_path(current_admin) do %>
              <i class="fa fa-circle-o"></i> Serviços
            <% end %>
          </li>
          <li>
            <%= link_to show_clients_path(current_admin) do %>
              <i class="fa fa-circle-o"></i> Clientes
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-book"></i> <span>Documentos</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> Termos</a></li>
          <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Licença</a></li>
          <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> FAQ</a></li>
        </ul>
      </li>
      <li>
        <a href="pages/mailbox/mailbox.html">
          <i class="fa fa-envelope"></i> <span>Mensagens</span>
          <small class="label pull-right bg-yellow">12</small>
        </a>
      </li>
      <li class="header">MAIS</li>
      <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Ajuda</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Contato para Suporte</span></a></li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      <% unless client_signed_in? or admin_signed_in? %>
        <%= link_to "Administração", new_admin_session_path , class: "btn-link" %>
      <% else %>
        <%= link_to "Gitlab", root_path , class: "btn-link" %>
      <% end %>
    </div>
	<!-- Default to the left -->
	<strong>Copyleft <span class="copy-left">&copy;</span> 2016 <a href="" class="btn-link"><b>Eletronjun</b></a>.</strong>
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <% if client_signed_in? %>
    <%= link_to client_path(current_client), class: "logo" do %>
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>ME</b>J</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Eletron</b>jun</span>
    <% end %>
  <% end %>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <% if client_signed_in? %>
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
    <% end %>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown notifications-menu">
          <% unless client_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-chevron-right"></i> Entrar
            </a>
            <ul class="dropdown-menu">
              <li class="header">Opções para o cliente</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li>
                    <%= link_to new_client_session_path do %>
                     <i class="fa fa-users text-aqua"></i> Já sou cliente
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_client_registration_path do %>
                      <i class="fa fa-edit text-green"></i> Cadastrar
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-chevron-right"></i> Sair
            </a>
            <ul class="dropdown-menu">
              <li class="header">Opções para o cliente</li>
              <li>
                <!-- inner menu: contains the actual data -->
                <ul class="menu">
                  <li>
                    <%= link_to root_path do %>
                     <i class="fa fa-reply text-aqua"></i> Voltar para o Início
                    <% end %>
                  </li>
                  <li>
                    <%= link_to destroy_client_session_path, method: :delete do %>
                      <i class="fa fa-power-off text-red"></i> Log Out
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          <% end %>
        </li>
        <!-- Notifications: style can be found in dropdown.less -->
        <li class="dropdown notifications-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-bell-o"></i> Menu do Cliente
          </a>
          <ul class="dropdown-menu">
            <li class="header">Opções para o cliente</li>
            <li>
              <!-- inner menu: contains the actual data -->
              <ul class="menu">
                <li>
                  <a href="#">
                   <i class="fa fa-users text-aqua"></i> Nossos Serviços
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-shopping-cart text-green"></i> Nossos Produtos
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-users text-red"></i> Nossos Clientes
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="fa fa-phone text-red"></i> Fale Conosco
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        <!-- User Account: style can be found in dropdown.less -->
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="hidden-xs"><i class="fa fa-building"></i> Eletronjun</span>
          </a>
          <ul class="dropdown-menu">
            <!-- User image -->
            <li class="user-header">
              <%= image_tag("/images/logo_small_eletronjun.png", alt: "Logo Eletronjun") %>
              <p>
                EletronJun
                <small>Engenharia Eletrônica Júnior</small>
              </p>
            </li>
            <!-- Menu Body -->
            <li class="user-body">
              <div class="row">
                <div class="col-xs-6 text-center">
                  <a href="http://eletronjun.com.br/"><i class="fa fa-check-circle text-green"></i> Site Oficial</a>
                </div>
                <div class="col-xs-6 text-center">
                  <a href="https://www.facebook.com/eletronjun/"><i class="fa fa-facebook text-blue"></i> Facebook</a>
                </div>
              </div>
              <!-- /.row -->
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar_control.html.erb
<aside class="control-sidebar control-sidebar-dark">
	<!-- Create the tabs -->
	<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
		<li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
		<li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
	</ul>
	<!-- Tab panes -->
	<div class="tab-content">
		<!-- Home tab content -->
		<div class="tab-pane active" id="control-sidebar-home-tab">
			<h3 class="control-sidebar-heading">Recent Activity</h3>
			<ul class="control-sidebar-menu">
				<li>
					<a href="javascript::;">
						<i class="menu-icon fa fa-birthday-cake bg-red"></i>
						<div class="menu-info">
							<h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
							<p>Will be 23 on April 24th</p>
						</div>
					</a>
				</li>
			</ul><!-- /.control-sidebar-menu -->

			<h3 class="control-sidebar-heading">Tasks Progress</h3>
			<ul class="control-sidebar-menu">
				<li>
					<a href="javascript::;">
						<h4 class="control-sidebar-subheading">
							Custom Template Design
							<span class="label label-danger pull-right">70%</span>
						</h4>
						<div class="progress progress-xxs">
							<div class="progress-bar progress-bar-danger" style="width: 70%"></div>
						</div>
					</a>
				</li>
			</ul><!-- /.control-sidebar-menu -->

		</div><!-- /.tab-pane -->
		<!-- Stats tab content -->
		<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
		<!-- Settings tab content -->
		<div class="tab-pane" id="control-sidebar-settings-tab">
			<form method="post">
				<h3 class="control-sidebar-heading">General Settings</h3>
				<div class="form-group">
					<label class="control-sidebar-subheading">
						Report panel usage
						<input type="checkbox" class="pull-right" checked>
					</label>
					<p>
						Some information about this general settings option
					</p>
				</div><!-- /.form-group -->
			</form>
			<p class="pull-left">Unhappy? We'll be sad to see you go.</p>
			<%= button_to "Cancel my account", client_registration_path, data: { confirm: "Are you sure?" }, method: :delete, class: "pull-right btn btn-danger btn-block" %>
		</div><!-- /.tab-pane -->
	</div>
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
		 immediately after the control sidebar -->
<div class="control-sidebar-bg"></div>

app/views/layouts/_sidebar_left.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/images/logo_small_eletronjun.png" class="img-circle" alt="User Image" style="max-width: 56px;">
      </div>
      <div class="pull-left info">
        <p><%= current_client.name.split[0] + " " + current_client.name.split[1] %></p>
        <small><i class="fa fa-circle text-success"></i> Online</small>
      </div>
    </div>
    <!-- search form -->
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Buscar...">
            <span class="input-group-btn">
              <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
              </button>
            </span>
      </div>
    </form>
    <!-- /.search form -->
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">MENU DE NAVEGAÇÃO</li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-pie-chart"></i>
          <span>Minha Conta</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li>
            <%= link_to client_path(current_client) do %>
              <i class="fa fa-circle-o"></i> Informações Gerais</li>
            <% end %>
          <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Meus produtos</a></li>
          <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Meus Serviços</a></li>
        </ul>
      </li>
      <li class="treeview">
        <a href="#">
          <i class="fa fa-book"></i> <span>Documentos</span>
          <i class="fa fa-angle-left pull-right"></i>
        </a>
        <ul class="treeview-menu">
          <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> Termos</a></li>
          <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Licença</a></li>
          <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> FAQ</a></li>
        </ul>
      </li>
      <li>
        <a href="pages/mailbox/mailbox.html">
          <i class="fa fa-envelope"></i> <span>Mensagens</span>
          <small class="label pull-right bg-yellow">12</small>
        </a>
      </li>
      <li class="header">MAIS</li>
      <li>
        <%= link_to edit_client_registration_path do %>
          <i class="fa fa-circle-o text-red"></i> <span>Configurações</span></li>
        <% end %>
      <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Ajuda</span></a></li>
      <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Canais de Atendimento</span></a></li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>EletronJun</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
	</head>

	<% if client_signed_in? %>
		<body class="hold-transition skin-green-light sidebar-mini">
			<div class="wrapper">
				<!-- Main Header -->
				<%= render  partial: "/layouts/header" %>

				<!-- Left side column. contains the logo and sidebar -->
				<%= render partial: "/layouts/sidebar_left" %>

				<!-- Content Wrapper. Contains page content -->
				<div class="content-wrapper">
					<%= yield %>
				</div><!-- /.content-wrapper -->

				<!-- Main Footer -->
				<%= render partial: "/layouts/footer" %>
			</div><!-- ./wrapper -->
		</body>

	<% elsif admin_signed_in? %>
		<body class="hold-transition skin-red-light sidebar-mini">
			<div class="wrapper">
				<!-- Main Header -->
				<%= render  partial: "/layouts/admin_header" %>

				<!-- Left side column. contains the logo and sidebar -->
				<%= render partial: "/layouts/admin_sidebar_left" %>

				<!-- Content Wrapper. Contains page content -->
				<div class="content-wrapper">
					<%= yield %>
				</div><!-- /.content-wrapper -->

				<!-- Main Footer -->
				<%= render partial: "/layouts/footer" %>
			</div><!-- ./wrapper -->
		</body>

	<% else %>
		<body class="layout-top-nav skin-yellow register-page">
			<!-- Main Header -->
			<%= render  partial: "/layouts/header" %>
			
			<!-- Content Wrapper. Contains page content -->
			<div class="content-wrapper">
				<%= yield %>
			</div><!-- /.content-wrapper -->

			<!-- Main Footer -->
			<%= render partial: "/layouts/footer" %>
		</body>
	<% end %>
</html>